name: g2_CI_Workflow

on: [push]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Aluga Testes Invalidos
      run: |
        cd Biblio
        gcc mainTestesAlugaInvalidos.c  alugaLivro.c abreArquivo.c -o mainTestesAlugaInvalidos
        ./mainTestesAlugaInvalidos
    - name: Build Aluga Testes Validos
      run: |
        cd Biblio
        gcc mainTestesAlugaValidos.c alugaLivro.c abreArquivo.c -o mainTestesAlugaValidos
        ./mainTestesAlugaValidos
    - name: Build Testes Validos 
      run: |
        cd Biblio
        gcc mainTestesValidos.c  addLivro.c abreArquivo.c removeLivro.c -o mainTestesValidos
        ./mainTestesValidos
    - name: Build Testes Invalidos 
      run: |
        cd Biblio
        gcc mainTestesInvalidos.c addLivro.c abreArquivo.c removeLivro.c -o mainTestesInvalidos 
        ./mainTestesInvalidos
    - name: Build Testes Login 
      run: |
        cd Sau
        gcc mainTesteLogin.c abreArquivo.c login.c -o mainTesteLogin
        ./mainTesteLogin
    - name: Build Testes Cadastro 
      run: |
        cd Sau
        gcc mainTesteCadastro.c abreArquivo.c cadastro.c -o mainTesteCadastro
        ./mainTesteCadastro
