name: g2_CI_Workflow

on: [push]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: entrar na pasta
      run: cd Biblio
    - name: Build Aluga Testes Invalidos
      run: gcc mainTestesAlugaInvalidos.c -lrt -lm -o mainTestesAlugaInvalidos
    - name: Build Aluga Testes Validos
      run: gcc mainTestesAlugaValidos.c -lrt -lm -o mainTestesAlugaValidos
    - name: Build Testes Validos 
      run: gcc mainTestesValidos.c -lrt -lm -o mainTestesValidos
    - name: Build Testes Invalidos 
      run: gcc mainTestesInvalidos.c -lrt -lm -o mainTestesInvalidos
