name: g2_CI_Workflow

on: [push]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: git clone https://gist.github.com/1f45a929aba4eb91f376.git minunit
    - name: Enter framework folder
      run: cd minunit
    - name: make teste
      run: make teste
