name: g2_CI_Workflow

on: [push]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Aluga Testes Invalidos
    - run: gcc Biblio/mainTestesAlugaInvalidos.c  alugaLivro.c abreArquivo.c -lrt -lm -o mainTestesAlugaInvalidos 
    - name: Build Aluga Testes Validos
    - run: gcc Biblio/mainTestesAlugaValidos.c alugaLivro.c abreArquivo.c -lrt -lm -o mainTestesAlugaValidos
    - name: Build Testes Validos 
    - run: gcc Biblio/mainTestesValidos.c alugaLivro.c abreArquivo.c -lrt -lm -o mainTestesValidos
    - name: Build Testes Invalidos 
    - run: gcc Biblio/mainTestesInvalidos.c alugaLivro.c abreArquivo.c -lrt -lm -o mainTestesInvalidos 
