name: g2_CI_Workflow

on: [push]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: entrar na pasta
      run: cd biblio
    - name: Build Aluga Testes Invalidos
      run: gcc mainTestAlugaInvalidos.c -lrt -lm -o mainTestAlugaInvalidos
    - name: Build Aluga Testes Validos
      run: gcc mainTestAlugaValidos.c -lrt -lm -o mainTestAlugaValidos
    - name: Build Testes Validos 
      run: gcc mainTestValidos.c -lrt -lm -o mainTestValidos
    - name: Build Testes Invalidos 
      run: gcc mainTestInvalidos.c -lrt -lm -o mainTestInvalidos
