name: g2_CI_Workflow

on: [push]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: entrar na pasta
      run: cd Biblio
    - name: Build Aluga Testes Invalidos
      run: gcc mainTesteAlugaInvalidos.c -lrt -lm -o mainTestAlugaInvalidos
    - name: Build Aluga Testes Validos
      run: gcc mainTesteAlugaValidos.c -lrt -lm -o mainTestAlugaValidos
    - name: Build Testes Validos 
      run: gcc mainTesteValidos.c -lrt -lm -o mainTestValidos
    - name: Build Testes Invalidos 
      run: gcc mainTesteInvalidos.c -lrt -lm -o mainTestInvalidos
